Lifted/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from .views import YourPostsListView
from .views import PostListView
from .views import PostDelete
from django.urls import path
from . import views


from .views import custom_403_view



urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.about, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('posts/', PostListView.as_view(), name='index'),
    path('post/create/', views.PostCreate.as_view(), name='post_create'),
    path('post/delete/<int:pk>/', PostDelete.as_view(), name='post_delete'),
    path('posts/<int:user_id>/', YourPostsListView.as_view(), name='your_posts'),
    path('post/update/<int:pk>/', views.PostUpdate.as_view(), name='posts_update'),
    path('comments/<int:comment_id>/delete/', views.delete_comment, name='comment_delete'),
    path('posts/<int:post_id>/add_comment/', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/add_photo/', views.add_photo, name='add_photo'),
    path('posts/detail/<int:post_id>/', views.posts_detail, name='detail'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse



# Create your models here.
class Image(models.Model):
    image = models.ImageField(upload_to='images/')
    description = models.CharField()

    def __str__(self):
        queryset = Image.objects.all()
        return self.description 



class Post(models.Model):
    description = models.CharField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.description} ({self.id})'
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'post_id': self.id})    

    class Meta:
        ordering = ['-created_at']



class Comment(models.Model):
    content = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)  
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.get_content_display()}"



class Photo(models.Model):
    url = models.CharField(max_length=200)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for post_id: {self.post_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Comment


class CommentForm(ModelForm):
  class Meta:
    model = Comment
    fields = ['content']

main_app/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .mixins import UserCanDeletePostMixin, UserCanUpdatePostMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.list import ListView
from django.shortcuts import render, redirect
from .models import Post, Comment, Photo
from django.contrib.auth import login
from django.urls import reverse_lazy
from .forms import CommentForm
import getpass
import boto3
import uuid
import os
# Create your views here.
def about(request):
  return render(request, 'home.html')


@login_required
def add_photo(request, post_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      Photo.objects.create(url=url, post_id=post_id)
    except Exception as e:
      print('An error occurred uploading file to S3')
      print(e)
  return redirect('detail', post_id=post_id)


@login_required
def home(request):
  return render(request, 'home.html')


@login_required
def all_posts(request):
    posts = Post.objects.all()
    photos = Photo.objects.all()
    return render(request, 'posts/index.html', {'posts': posts, 'photos': photos})


@login_required
def posts_detail(request, post_id):
  post = Post.objects.get(id=post_id)
  comment_form = CommentForm()
  return render(request, 'posts/detail.html', {
    'post': post, 'comment_form': comment_form
  })


def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


def get_logged_in_username():
    username = getpass.getuser()
    return username


@login_required
def add_comment(request, post_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user 
            new_comment.post_id = post_id
            new_comment.save()
    return redirect('detail', post_id=post_id)


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if comment.user == request.user:
        post_id = comment.post.id  
        comment.delete()
        return redirect('detail', post_id=post_id)
    else:
        return redirect('detail', post_id=comment.post.id) 
    


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['description']
    template_name = 'main_app/post_form.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        post = form.save(commit=False)
        post.save()
        image = self.request.FILES.get('photo-file', None)  
        if image:
            url = self.upload_image_to_s3(image)
            Photo.objects.create(url=url, post_id=post.id)

        return super().form_valid(form)

    def upload_image_to_s3(self, image_file):
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + image_file.name[image_file.name.rfind('.'):]

        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(image_file, bucket, key)
            return f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
            return None



class CommentCreate(LoginRequiredMixin, CreateView):
  model = Comment
  fields = '__all__'



class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'posts/index.html' 
    context_object_name = 'object_list'  



class YourPostsListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'posts/your_posts.html'  
    context_object_name = 'your_posts' 

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user)



class PostDelete(UserCanDeletePostMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('index')



class PostUpdate(UserCanUpdatePostMixin, UpdateView):
    model = Post
    fields = ['description']
    success_url = reverse_lazy('index')
    template_name = 'main_app/post_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        post = form.save(commit=False)
        post.save()

        image = self.request.FILES.get('photo-file', None) 
        if image:
            url = self.upload_image_to_s3(image)
            Photo.objects.create(url=url, post_id=post.id)

        return super().form_valid(form)

    def upload_image_to_s3(self, image_file):
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + image_file.name[image_file.name.rfind('.'):]

        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(image_file, bucket, key)
            return f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
            return None




def custom_403_view(request):
    return render(request, '403.html', status=403)

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lifted</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
    <div id="nav">
    <nav class="navbar bg-body-tertiary">
        <div class="container">
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'index' %}">
              <img src="https://i.imgur.com/03rxreM.png" alt="Lifted" width="70" height="80">
            </a>
            <a id="nav" class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'your_posts' user.id %}" id="nav">Profile</a>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <a id="nav" class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'post_create' %}">Show What You Lifted</a>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <a id="nav" class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'logout' %}">Log Out</a>
          {% else %}
            <a id="nav" class="link-offset-2 link-underline link-underline-opacity-0"href="{% url 'home' %}">About</a>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <a id="nav" class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'signup' %}">Sign Up</a>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <a id="nav" class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'login' %}">Log In</a>
          {% endif %}
        </div>
    </nav>
    </div>
    <div id="header">
    </div>
    <div id="content">






























    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    {% block content %}
    {% endblock %}























</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div id="home">
<h1>ＬＩＦＴＥＤ</h1>
<br>
<h2>Your House can be Our Home</h2>
<br>
<p>Being hardworking and underpaid most of our lives, we have finally had enough.</p>
<p>We decided to start taking from the fortunate, and wanted to show the world, but it was not that easy.</p>
<p>ＬＩＦＴＥＤ was created to impress the world with what we achieved.</p>
<p>We did not want to be the only ones with this kind of access, so ＬＩＦＴＥＤ is now open to everyone with this passion.</p>
<br>
<p>Steal. Post. Done.</p>
<br>
<h1>ＬＩＦＴＥＤ</h1>
</div>
{% endblock %}

main_app/templates/index.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Index Page</title>
</head>
<body>
    <h1>templates/index.html</h1>
    <ul>
        {% for post in object_list %}
            <li>{{ post.description }}</li>
        {% endfor %}
    </ul>
</body>
</html>
{% endblock %}

main_app/templates/main_app/post_form.html
{% extends 'base.html' %}

{% block content %}

<h1>Add your post!</h1>
<br>
<br>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <br>
    <input type="file" name="photo-file">
    <br><br>
    <input class="btn btn-outline-dark" type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/posts/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Post Details</h1>
<br>
<br>
<div class="row">
  <div class="col s6">
    <div class="card">
      <span class="card-title"><strong>{{ post.user.username }}</strong>'s Post</span>
      <p>{{ post.description|linebreaks }}</p>
    </div>
    <div class="card-action">
      <form method="post" action="{% url 'post_delete' post.id %}">
        {% csrf_token %}
        <button class="btn btn btn-dark" type="submit">Delete Post</button>
      </form>
      <a class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'posts_update' post.id %}">Edit</a>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_comment' post.id %}" method="POST">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <input type="submit" class="btn btn btn-dark" value="Add Comment">
    </form>
    <br>
    <h2>Comments</h2>
    {% for comment in post.comment_set.all %}
      <p>
        <p><strong>{{ comment.user.username }}</strong>: {{ comment.content }}</p>
        {% if comment.user == request.user %}
        <a class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'comment_delete' comment.id %}">Delete</a>
        {% endif %}
      </p>
      {% empty %}
      <p>No comments yet</p>
    {% endfor %}
    <br>
    <br>
  </div>
  <div class="row2 image-container">
    <form action="{% url 'add_photo' post.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <button type="submit" class="btn btn btn-dark">Upload Photo</button>
    </form>
    {% for photo in post.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}" style="max-width: 200px; max-height: 200px;">
      {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
  </div>
</div>



{% endblock %}

main_app/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}

<h1>The Wall of Fame</h1>
<br>
<br>
<div class="row">
    <div class="col s6">
        <div class="card">
        {% for post in object_list %}
            <a class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'detail' post.id %}">
                <div class="shadow-sm p-3 mb-5 bg-body-tertiary rounded">
                    <p>{{ post.description }}</p>
                    <div class="row2 image-container">
                        {% for photo in post.photo_set.all %}
                            <img class="responsive-img card-panel" src="{{photo.url}}" style="max-width: 200px; max-height: 200px;">
                        {% empty %}
                            <div class="card-panel teal-text center-align">No Photos Uploaded</div>
                        {% endfor %}
                    </div>
                </div>
            </a>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

main_app/templates/posts/your_posts.html
{% extends 'base.html' %}

{% block content %}

<h1>Your Posts</h1>
<br>
<br>
<div class="row">
    <div class="col s6">
        <div class="card">
        {% for post in object_list %}
            <a class="link-offset-2 link-underline link-underline-opacity-0" href="{% url 'detail' post.id %}">
                <div class="shadow-sm p-3 mb-5 bg-body-tertiary rounded">
                    <p>{{ post.description }}</p>
                    <div class="row2 image-container">
                        {% for photo in post.photo_set.all %}
                            <img class="responsive-img card-panel" src="{{photo.url}}" style="max-width: 200px; max-height: 200px;">
                        {% empty %}
                            <div class="card-panel teal-text center-align">No Photos Uploaded</div>
                        {% endfor %}
                    </div>
                </div>
            </a>
        {% endfor %}
        </div>
    </div>
</div>

{% endblock %}